import type {Metadata} from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen justify-between bg-gray-50">
                <NavBar/>
                <main className="flex-grow scroll-auto">
                    {children}
                </main>
                <Footer/>
            </body>
        </html>
    );
}
